flowchart TB
    
    %% Colors %%
    %% Rationale: Green is often associated with "action," "go," and "processing," which fits the nature of execution blocks that actively transform or process data.
    classDef green fill:#28a745,stroke:#000,stroke-width:2px,color:#fff;
    %% Rationale: Blue is often associated with "organization," "grouping," and "collective operations." It provides a calm, structural feel, appropriate for blocks that group or batch items.
    classDef blue fill:#2374f7,stroke:#000,stroke-width:2px,color:#fff;
    %% Rationale: Orange is often linked with "storage" or "holding" phases and is visually distinct. Buffer blocks temporarily store items before they are processed, so orange can indicate this intermediary state.
    classDef orange fill:#f28c28,stroke:#000,stroke-width:2px,color:#fff;


    subgraph Buffer
        %% direction TD
        BB("⧉ BufferBlock<T>"):::orange
        BrB("⊛ BroadcastBlock<T>"):::orange
        WOB("⨀ WriteOnceBlock<T>"):::orange
    end
    
    subgraph Grouping
        %% direction TD
        BaB("⌗ BatchBlock<T>"):::blue
        JB("⊛ JoinBlock<T1, T2>"):::blue
        BJB("⟟ BatchedJoinBlock<T1, T2>"):::blue
    end

    subgraph Execution
        %% direction TD
        AB("◊ ActionBlock<T>"):::green
        TB("‡ TransformBlock<T, U>"):::green
        TMB("⊕ TransformManyBlock<TInput, TOutput>"):::green
    end