flowchart LR
    subgraph Execution
        %% direction TD
        AB("◊ ActionBlock<T>")
        TB("‡ TransformBlock<T, U>")
        TMB("⊕ TransformManyBlock<TInput, TOutput>")
    end
    
    subgraph Grouping
        %% direction TD
        BaB("⌗ BatchBlock<T>")
        JB("⊛ JoinBlock<T1, T2>")
        BJB("⟟ BatchedJoinBlock<T1, T2>")
    end
    
    subgraph Buffer
        %% direction TD
        BB("⧉ BufferBlock<T>")
        BrB("⊛ BroadcastBlock<T>")
        WOB("⨀ WriteOnceBlock<T>")
    end
