flowchart LR
    classDef green fill:#28a745,stroke:#000,stroke-width:2px,color:#fff;
    classDef blue fill:#2374f7,stroke:#000,stroke-width:2px,color:#fff;
    classDef orange fill:#f28c28,stroke:#000,stroke-width:2px,color:#fff;
    
    lB("‡ Transform Block\nLoad Bitmaps"):::green
    cCB("‡ Transform Block\nCreate Composite Bitmap"):::green
    dCB("◊ Action Block\nDisplay Composite Bitmap"):::green
    oC("◊ Action Block\nOperation Cancelled"):::green

    subgraph main[ ]
        lB
        cCB
        dCB
    end

    lB -.-> cCB
    cCB -.-> dCB
    cCB -.-> oC

    style main fill:none,stroke:none
