flowchart LR

    lB("‡ Transform Block 
    Load Bitmaps")

    cCB("‡ Transform Block 
    Create Composite Bitmap")

    dCB("◊ Action Block 
    Display Composite Bitmap")

    oC("◊ Action Block 
    Operation Cancelled")

    lB .-> cCB .-> dCB
    cCB .-> oC
