flowchart LR
    lB("‡ Transform Block\nLoad Bitmaps")
    cCB("‡ Transform Block\nCreate Composite Bitmap")
    dCB("◊ Action Block\nDisplay Composite Bitmap")
    oC("◊ Action Block\nOperation Cancelled")

    subgraph main[ ]
        lB
        cCB
        dCB
    end

    lB -.-> cCB
    cCB -.-> dCB
    cCB -.-> oC

    style main fill:none,stroke:none
